# 1. Notifications
notifications:
  slack:
    rooms:
      - secure: "hdWzHM/Q0yAcJjj3n9unSk/DgCX3XNJnrso4BappaojFBHN0MDKSgD+uYOxLPEJbtz8wP0UFSfI95BZDwd4Z7pPITL6GQD2f9dNO+I23CmdcBXMd3EM5UR76Lkkh86Yph1OfNnzAnkqXcZBXrskfLEzhEBHq+ebxTW31DTpqTLVM1LYqRZ3LCUoKGLU8l6kLhuJDBfa27xc2YRc2KvtXiIUpt+/LDZ5xjTpxCsYneNqFckmejvNvfMgcIAMZDkykV1jXtsRioT1Kg+qwT4K9fs7sElErw428m/4iRjwzKf7G/mY9viVgRK1TZgBHwsb8tb835Kt5eFRjAmvjLwZuPMxuOTvAy14/GgAsB4x+vLLiSo571KOi/ZIoIJVm5dNNVzc/v4GBSbN6NAu4C7GOjMZpBFkcLtEzx6gpvKNk+rnnfvHrF7fMAyZOWS+5rIJxYbbMp4IEzkLb0kAgdU/gtPEuZfYGArSF1moGopX9kIdgcfeHVgtUOlJc/L6PqE09IDzNLaeF6v2a6UTeoXnM86yXED+0LNf0h+kFZr4lmoMwu+xnMD5GS05PbBqUytsRx/+JnWmswbPtNprOd0qSZZ/edgrL8R7uTvm9N38AEUvBkh6bUmI7VahbczV0ZRzxVi+2kJTgp2e+quYYp1M6BxbhFH/o3Zx4RFDS8WFLyCE=" # atex-ci
      - secure: "ZVRPmzKAPkv8OrjID0KwwhYlJxXXaStvQG3/S0Ioq1FyF5gHunZvBx2pgoLAS8VCEjHG4ASRoQGhB9LCFOpL+om68Xndwa9QJ1A1MrSymu4RI/doeyYeIot9fxn6O64Qo6+OOmLna+vrg6YcvxgkL0Vf/++0dB7Am8Jj2dhw45MBhQiD/9+nriIpGOYTcx+eKvBhcLoPtCqbWHwyEn2R/i1zc62uXmQ5K9I91SuVndWxKulRCTy7iJnSx+B4OEbYI0gqq23tRT1E8dgeRPM9IcEfbf4HWR5zFxgBt4gLrh4Qx4jxSBTXchyvbEZDJR9OzLya2CuNJT8co2t1ZNuJ78ZaNVcIWUuTKZxWCDdvqHpB/fZhJqR6OMrOFRhieth+GkdANc3D73eStIDKyszESHvrxzy7sMMJFwRzhGnZM2YVixBrxk1k8sdL7amlwgaggFDR3+5af/rxMUjoISZT339dCj+m7q3YvcCW54/+PEOxvyoP9dFCKYxyBrreBmSnLwV8Qq3BQQ44vChO+96KT3BQE1l+fK+Sfkpnwc6pg3s5aB4ZW7Td9OwywkBdMK3GJRPOFi04MLrowVzsYQyic3ytB9oucWZZ2+RHlWQbiylkgvNN2jtYtYlaYMRbZfjHlVBnfPVhCTpSxBvg67dAFnTd7NrbfGQcd1jabmsfy+M=" # cloud-ci
    on_success: change
    on_pull_requests: false

# 2. Env
# env:

# 3. Git
# git:
branches:
  except:
    - /^f\// # feature branches require PR
    - /^v\d+\.\d+\.\d+$/ # npm-publish-tag

# 4. Bootstrap
os: linux
dist: trusty
sudo: false
language:
  - node_js
node_js:
  - node
# addons:
before_cache: ./.travis.sh before_cache
cache:
  directories:
    - $HOME/.local
    - $HOME/.npm
    - $HOME/.pip-cache/
    - $HOME/Library/Caches/Homebrew
    - /tmp/support-firecloud.cache
    - node_modules

# 5. Steps
before_install: ./.travis.sh before_install
install: ./.travis.sh install
before_script: ./.travis.sh before_script
script: ./.travis.sh script
after_success: ./.travis.sh after_success
after_failure: ./.travis.sh after_failure
after_script: ./.travis.sh after_script

# 6. Deploy
before_deploy: ./.travis.sh before_deploy
# deploy:
after_deploy: ./.travis.sh after_deploy
